# Generated by Django 4.1 on 2022-08-26 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=180, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('major', models.CharField(blank=True, max_length=180, null=True)),
                ('type', models.BooleanField(choices=[('student', 'دانش اموز'), ('consultant', 'مشاور')], default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records', models.CharField(blank=True, max_length=180, null=True)),
                ('image', models.ImageField(upload_to='img/consultant')),
                ('telegram', models.CharField(blank=True, max_length=180, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=180, null=True)),
                ('instagram', models.CharField(blank=True, max_length=180, null=True)),
                ('tel', models.CharField(blank=True, max_length=180, null=True)),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
