# Generated by Django 4.1 on 2022-08-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('student', 'دانش اموز'), ('consultant', 'مشاور')], default=0, max_length=10),
        ),
    ]
