# Generated by Django 4.1 on 2022-11-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantprofile',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='ایمیل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/consultant', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='price',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='tel',
            field=models.CharField(default=1, max_length=180, verbose_name='شماره تماس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='university',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
