# Generated by Django 4.1 on 2022-08-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('None', 'نامشخص'), ('male', 'مرد'), ('female', 'زن')], default=0, max_length=10),
        ),
    ]
